import streamlit as strl
import pandas as pd
import os
from src.processor import TicketProcessor
from src.llm_helper import LLMDeduplicatorHelper

# Set up clean screen presentation constraints
strl.set_page_config(page_title="DedupeAI Triage Console", layout="wide")

# Instantiate processing and AI engines
processor = TicketProcessor()
ai_helper = LLMDeduplicatorHelper()

strl.title("🛠️ DedupeAI — Production Support Triage Console")
strl.markdown("---")

# Layout separation structure: Intake Forms vs Reporting Workbench Panels
col_left, col_right = strl.columns([2, 3])

with col_left:
    strl.subheader("📥 Incident Intake Channel")
    
    # Guidelines Option: Instant injection of 5-20 sample records for demo flow clarity
    strl.markdown("**Demo Quick-Inject Scenarios:**")
    btn_col1, btn_col2 = strl.columns(2)
    
    preset_text = ""
    with btn_col1:
        if strl.button("Simulate Database Error"):
            preset_text = "FATAL ERROR: Remaining connection slots are fully exhausted for non-replication superusers. Pooling thresholds maxed out."
    with btn_col2:
        if strl.button("Simulate K8s Storage Crash"):
            preset_text = "CRITICAL ALERT: Root volume filesystem space /dev/sda1 capacity warning log has exceeded 94% on cluster node worker-03."

    # Core user text area input box
    input_text = strl.text_area(
        "Paste Incoming System Error Log / Support Ticket:",
        value=preset_text if preset_text else "",
        height=200,
        placeholder="Drop raw server logs, stacktraces, or user incident reports here..."
    )
    
    fire_analysis = strl.button("Execute Agent Triage Loop", type="primary")

with col_right:
    strl.subheader("📊 Triage Analysis Workbench")
    
    if fire_analysis and input_text.strip():
        with strl.spinner("Running Local Vector Mapping & AI Guardrail Verifications..."):
            
            # STAGE 2: Programmatic backend vector matching
            matches = processor.find_top_matches(input_text, top_n=3)
            
            # STAGE 3: AI structured classification generation
            ai_verdict = ai_helper.verify_duplicate_status(input_text, matches)
            
            # STAGE 4: UI rendering and output metrics display
            if ai_verdict.get("is_duplicate"):
                strl.error(f"🚨 DUPLICATE DETECTED (AI Confidence Match: {ai_verdict.get('confidence_percentage')}%)")
            else:
                strl.success("✅ UNIQUE STANDALONE TICKET VERIFIED")
                
            strl.markdown(f"**Recommended Action:** `{ai_verdict.get('recommended_action')}`")
            strl.markdown(f"**AI Rationale:** *{ai_verdict.get('reasoning')}*")
            
            strl.markdown("---")
            strl.markdown("**Top Mathematical Database Match Comparisons (SQLite):**")
            
            # Render database structures directly as an interactive visualization grid
            match_df = pd.DataFrame(matches)
            if not match_df.empty:
                strl.dataframe(
                    match_df[['ticket_id', 'category', 'title', 'similarity_score']], 
                    use_container_width=True,
                    hide_index=True
                )
            
            # Compile automated Markdown report file content
            report_content = f"""# Incident Triage Triage Report
Generated by DedupeAI Prototype Solution.

## Incoming Ticket Payload
{input_text}

## Classification Metrics
* **Is Duplicate Instance:** {ai_verdict.get('is_duplicate')}
* **Identified Target Duplicate ID:** {ai_verdict.get('target_duplicate_id')}
* **Confidence Level:** {ai_verdict.get('confidence_percentage')}%
* **System Logic Reasoning:** {ai_verdict.get('reasoning')}
* **Enforced Action:** {ai_verdict.get('recommended_action')}

---
Report cached under output directories for compliance validation audits.
"""
            # Mandatory file save loop: exports file to your local disk outputs folder
            os.makedirs("outputs", exist_ok=True)
            output_file_name = f"outputs/triage_report_{ai_verdict.get('target_duplicate_id') or 'unique'}.md"
            with open(output_file_name, "w") as f:
                f.write(report_content)
            
            # Provide clean download UI trigger button to user
            strl.download_button(
                label="📥 Export Triage Report as Markdown File",
                data=report_content,
                file_name=os.path.basename(output_file_name),
                mime="text/markdown"
            )
            
    elif fire_analysis:
        strl.warning("Please supply a valid text body input string or click a demo scenario.")
    else:
        strl.info("System idle. Paste raw technical logs into the intake console or run a simulation preset to verify operational paths.")
